version: '3.8'

services:
  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    image: jackson300802/tmdt-dacn-authentication-service:latest
    ports:
      - "3001:3001"
    env_file:
      - ./authentication-service/.env
    container_name: authentication-service
    networks:
      - ecommerce-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: jackson300802/tmdt-dacn-product-service:latest
    ports:
      - "3002:3002"
    env_file:
      - ./product-service/.env
    container_name: product-service
    networks:
      - ecommerce-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: jackson300802/tmdt-dacn-order-service:latest
    ports:
      - "3003:3003"
    env_file:
      - ./order-service/.env
    container_name: order-service
    networks:
      - ecommerce-network

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    image: jackson300802/tmdt-dacn-inventory-service:latest
    ports:
      - "3004:3004"
    env_file:
      - ./inventory-service/.env
    container_name: inventory-service
    networks:
      - ecommerce-network
  
  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    image: jackson300802/tmdt-dacn-admin-service:latest
    ports:
      - "3009:3009"
    env_file:
      - ./admin-service/.env
    container_name: admin-service
    networks:
      - ecommerce-network
  
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    image: jackson300802/tmdt-dacn-cart-service:latest
    ports:
      - "3005:3005"
    env_file:
      - ./cart-service/.env
    container_name: cart-service
    networks:
      - ecommerce-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: jackson300802/tmdt-dacn-api-gateway:latest
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
